apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: xx.xx.xx.xx
etcd:
  endpoints:
  - https://10.10.40.11:2379
  - https://10.10.40.12:2379
  - https://10.10.40.13:2379
  caFile: /etc/etcd/ca.pem
  certFile: /etc/etcd/kubernetes.pem
  keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 10.30.0.0/24
apiServerCertSANs:
- ww.ww.ww.ww
apiServerExtraArgs:
  apiserver-count: "3"
