# -*- mode: ruby -*-                                                                                                                                                                                               
# vi: set ft=ruby :

masterNr = 3
masterIP = "10.10.40.1"
Vagrant.configure(2) do |config|
# Disabled VirtualBox Guest updates
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  (1..masterNr).each do |i|
    config.vm.define "master#{i}" do |node|
    #config.vm.define vm_name = "master#{i}"
      node.vm.box = "debian/contrib-stretch64"
      node.vm.box_version = "=9.4.0"
      node.vm.hostname = "master#{i}"

      # Create a private network, which allows host-only access to the machine
      # using a specific IP.
      # This is the docker network
      #config.vm.network "private_network", ip: "10.10.10.40., auto_config: false
      privateIP = masterIP + i.to_s
      node.vm.network "private_network", ip: privateIP
      node.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        # vb.cpus = 1

        # Set the vboxnet interface to promiscous mode so that the docker veth
        # interfaces are reachable
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end
     
      #config.vm.provision "shell", inline: $script
      node.vm.provision "file", source: "./files", destination: "$HOME/files"
      node.vm.provision "shell", path: "./bin/provisioner.sh"
    end
  end
end
