# -*- mode: ruby -*-                                                                                                                                                                                               
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Disabled VirtualBox Guest updates
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.vm.box = "debian/contrib-stretch64"
  config.vm.box_version = "=9.4.0"
  config.vm.hostname = "master1"
  config.vm.define vm_name = "master1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # This is the docker network
  config.vm.network "private_network", ip: "10.10.0.2", auto_config: false
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    # vb.cpus = 1

    # Set the vboxnet interface to promiscous mode so that the docker veth
    # interfaces are reachable
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
 
  #config.vm.provision "shell", inline: $script
  config.vm.provision "file", source: "./files", destination: "$HOME/files"
  config.vm.provision "shell", path: "./bin/provisioner.sh"
end
